### ISSUE TITLE
Created times of history entries are inconsistently generated

### ISSUE THREAD

**Issue by PeterJCLaw** [thread/routemaster#89]
The `History` model records the `created` time of each entry, however these are not always consistently generated. In some parts of the code they are unspecified, meaning that the default from the model (`datetime.datetime.now(dateutil.tz.tzutc())`) is used, while elsewhere it is specified as `sqlalchemy.func.now()`.

The latter ends up as `NOW()` in the SQL, which is the ~`COMMIT`~ start time of the transaction on the database host. Code which creates two `History` entries using different mechanisms and/or timing de-sync between the Routemaster server and the database host can therefore cause odd artefacts in the history.

This is unfortunately not a theoretical issue -- the first two history entries for a label reliably have `created` values which are back to front.

Thankfully Routemaster is consistent about using `History.id` for ordering, so its behaviour is always correct in this regard; this issue is just one of correctness in the history data.

**Comment by prophile** [comment]
`now()` is not the commit time of the transaction, it's the start time of the transaction. It can't be the commit time of the transaction because the data already has to be written to disk by commit time.

**Comment by prophile** [comment]
(IMO we should standardise on `sqlalchemy.func.now()` given the choice—this would be consistent with triggered edits à la `AutoUpdatedField`).

**Comment by PeterJCLaw** [comment]
> `now()` is not the commit time of the transaction, it's the start time of the transaction. It can't be the commit time of the transaction because the data already has to be written to disk by commit time.

Ah, yeah, of course. That also explains why the `create_label` logic works the way around it does.
Have edited the description to clarify.
